### ISSUE TITLE
config.json error

### ISSUE THREAD

**Issue by 4mlsx** [openai/dallify-discord-bot#6] opened 2023-02-12 04:20 UTC
![Screenshot_2023-02-12-09-47-34-82_dce875ef40efa4e902b2719365b6f678.jpg](https://user-images.githubusercontent.com/124343610/218292812-b5c5447f-08bd-45b3-8868-542c1750d98f.jpg)

I put all the secrets according to the constants someone help me with this error

**Comment by Kav-K** [comment] 2024-01-03 20:45
Hi!

@4mlsx Can you please share your `config.json` file with all the sensitive tokens removed so I can see what's wrong?

**Comment by Kav-K** [comment] 2024-01-07 07:56
@4mlsx We'll close this out since this is old, please feel free to reopen if still experiencing this, but this is not locally reproducible for me.

**Closed as completed** 2024-01-09 18:51 UTC
